# Generated by Django 3.1.6 on 2021-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collagemodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
